### ISSUE TITLE
jd_zoo.js最新的出现致命错误

### ISSUE THREAD

**Issue by hdstar2009** [yangtingxiao/QuantumultX#31]
以前脚本出错不影响运行，现在出现以下错误，脚本完全不执行，一行日志都不出

(node:1768) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'acquiredScore' of undefined
    at dealReturn (/scripts/jd_zoo.js:742:46)
    at /scripts/jd_zoo.js:540:9
    at got.post.then.message (/scripts/jd_zoo.js:955:5772)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1768) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1768) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:1768) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'acquiredScore' of undefined
    at dealReturn (/scripts/jd_zoo.js:742:46)
    at /scripts/jd_zoo.js:540:9
    at got.post.then.message (/scripts/jd_zoo.js:955:5772)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:1768) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1768) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'acquiredScore' of undefined
    at dealReturn (/scripts/jd_zoo.js:742:46)
    at /scripts/jd_zoo.js:540:9
    at got.post.then.message (/scripts/jd_zoo.js:955:5772)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by hdstar2009** [comment]
可能看错，等我再核实。
