### ISSUE TITLE
抽奖机有报错

### ISSUE THREAD

**Issue by hdstar2009** [yangtingxiao/QuantumultX#46]
❗️京东抽奖机, 错误!
TypeError: Cannot read property 'nickname' of undefined
    at /ql/scripts/jd_lotteryMachine.js:86:38
    at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/ql/scripts/jd_lotteryMachine.js:374:4791)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by yangtingxiao** [comment]
昵称没取到导致的
