### ISSUE TITLE
jd_lotteryMachine 更新时间：2020-12-22 14:34 第3 4 5个抽奖活动报错

### ISSUE THREAD

**Issue by 345784078** [yangtingxiao/QuantumultX#8]
开始第3个抽奖活动

❗️京东抽奖机, 错误!
TypeError: Cannot read property 'undefined' of undefined
    at eval (eval at main (/home/runner/work/jd_scripts/jd_scripts/jd_lotteryMachine.js:30:5), <anonymous>:136:97)
    at got.post.then.message (eval at main (/home/runner/work/jd_scripts/jd_scripts/jd_lotteryMachine.js:30:5), <anonymous>:375:5694)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by yangtingxiao** [comment]
收到。更新试一下
